name: Deploy Asp Net core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Display dotnet version
        run: dotnet --version
        
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Publish
        run: |
          dotnet publish -c Release -o /home/compar/publish/

      - name: Restart API Service
        run: |
         sudo systemctl restart api.service
        
